package org.zkpk.cs.mapper;

import java.util.List;
import java.util.Map;

import org.zkpk.cs.entity.SysOrganization;

public interface SysOrganizationMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_organization
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String soId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_organization
	 * @mbg.generated
	 */
	int insert(SysOrganization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_organization
	 * @mbg.generated
	 */
	int insertSelective(SysOrganization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_organization
	 * @mbg.generated
	 */
	SysOrganization selectByPrimaryKey(String soId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_organization
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(SysOrganization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_organization
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SysOrganization record);

	List<SysOrganization> selectSysOrganizationListByParameter(Map<String, Object> parameterMap);
}