package org.zkpk.cs.mapper;

import java.util.List;
import java.util.Map;

import org.zkpk.cs.dto.SysResourceDto;
import org.zkpk.cs.entity.SysResource;

public interface SysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String srId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated
     */
    int insert(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated
     */
    int insertSelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated
     */
    SysResource selectByPrimaryKey(String srId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysResource record);

	List<SysResource> selectSysResourceListByParameter(Map<String, Object> parameterMap);

	List<SysResourceDto> selectAdminMenuResourceDto();

	List<SysResourceDto> selectMenuResourceDtoByUserId(String userId);

	SysResource selectMenuResourceByRightParentTrId(String parentSrId);

}