package org.zkpk.cs.mapper;

import java.util.List;

import org.zkpk.cs.dto.SysRoleResourceDto;
import org.zkpk.cs.entity.SysRoleResource;

public interface SysRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String srrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated
     */
    int insert(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated
     */
    int insertSelective(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated
     */
    SysRoleResource selectByPrimaryKey(String srrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysRoleResource record);

	List<SysRoleResourceDto> selectRoleResourceListByRoleId(String roleId);

	int batchInsertSysRoleResource(List<SysRoleResource> newsysroleresourcelist);

	int batchDeleteSysRoleResource(List<String> delidlist);
}