package org.zkpk.cs.entity;

import java.io.Serializable;
import java.util.Date;

public class SysOrganization implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_organization.so_id
	 * @mbg.generated
	 */
	private String soId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_organization.parent_so_id
	 * @mbg.generated
	 */
	private String parentSoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_organization.org_code
	 * @mbg.generated
	 */
	private String orgCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_organization.org_name
	 * @mbg.generated
	 */
	private String orgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_organization.org_type
	 * @mbg.generated
	 */
	private String orgType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_organization.description
	 * @mbg.generated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_organization.is_available
	 * @mbg.generated
	 */
	private Boolean isAvailable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_organization.priority
	 * @mbg.generated
	 */
	private Integer priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_organization.create_by
	 * @mbg.generated
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_organization.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_organization.update_by
	 * @mbg.generated
	 */
	private String updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_organization.update_time
	 * @mbg.generated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_organization.is_deleted
	 * @mbg.generated
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_organization
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_organization.so_id
	 * @return  the value of sys_organization.so_id
	 * @mbg.generated
	 */
	public String getSoId() {
		return soId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_organization.so_id
	 * @param soId  the value for sys_organization.so_id
	 * @mbg.generated
	 */
	public void setSoId(String soId) {
		this.soId = soId == null ? null : soId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_organization.parent_so_id
	 * @return  the value of sys_organization.parent_so_id
	 * @mbg.generated
	 */
	public String getParentSoId() {
		return parentSoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_organization.parent_so_id
	 * @param parentSoId  the value for sys_organization.parent_so_id
	 * @mbg.generated
	 */
	public void setParentSoId(String parentSoId) {
		this.parentSoId = parentSoId == null ? null : parentSoId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_organization.org_code
	 * @return  the value of sys_organization.org_code
	 * @mbg.generated
	 */
	public String getOrgCode() {
		return orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_organization.org_code
	 * @param orgCode  the value for sys_organization.org_code
	 * @mbg.generated
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode == null ? null : orgCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_organization.org_name
	 * @return  the value of sys_organization.org_name
	 * @mbg.generated
	 */
	public String getOrgName() {
		return orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_organization.org_name
	 * @param orgName  the value for sys_organization.org_name
	 * @mbg.generated
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName == null ? null : orgName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_organization.org_type
	 * @return  the value of sys_organization.org_type
	 * @mbg.generated
	 */
	public String getOrgType() {
		return orgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_organization.org_type
	 * @param orgType  the value for sys_organization.org_type
	 * @mbg.generated
	 */
	public void setOrgType(String orgType) {
		this.orgType = orgType == null ? null : orgType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_organization.description
	 * @return  the value of sys_organization.description
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_organization.description
	 * @param description  the value for sys_organization.description
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_organization.is_available
	 * @return  the value of sys_organization.is_available
	 * @mbg.generated
	 */
	public Boolean getIsAvailable() {
		return isAvailable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_organization.is_available
	 * @param isAvailable  the value for sys_organization.is_available
	 * @mbg.generated
	 */
	public void setIsAvailable(Boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_organization.priority
	 * @return  the value of sys_organization.priority
	 * @mbg.generated
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_organization.priority
	 * @param priority  the value for sys_organization.priority
	 * @mbg.generated
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_organization.create_by
	 * @return  the value of sys_organization.create_by
	 * @mbg.generated
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_organization.create_by
	 * @param createBy  the value for sys_organization.create_by
	 * @mbg.generated
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy == null ? null : createBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_organization.create_time
	 * @return  the value of sys_organization.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_organization.create_time
	 * @param createTime  the value for sys_organization.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_organization.update_by
	 * @return  the value of sys_organization.update_by
	 * @mbg.generated
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_organization.update_by
	 * @param updateBy  the value for sys_organization.update_by
	 * @mbg.generated
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy == null ? null : updateBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_organization.update_time
	 * @return  the value of sys_organization.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_organization.update_time
	 * @param updateTime  the value for sys_organization.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_organization.is_deleted
	 * @return  the value of sys_organization.is_deleted
	 * @mbg.generated
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_organization.is_deleted
	 * @param isDeleted  the value for sys_organization.is_deleted
	 * @mbg.generated
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_organization
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		SysOrganization other = (SysOrganization) that;
		return (this.getSoId() == null ? other.getSoId() == null : this.getSoId().equals(other.getSoId()))
				&& (this.getParentSoId() == null ? other.getParentSoId() == null
						: this.getParentSoId().equals(other.getParentSoId()))
				&& (this.getOrgCode() == null ? other.getOrgCode() == null
						: this.getOrgCode().equals(other.getOrgCode()))
				&& (this.getOrgName() == null ? other.getOrgName() == null
						: this.getOrgName().equals(other.getOrgName()))
				&& (this.getOrgType() == null ? other.getOrgType() == null
						: this.getOrgType().equals(other.getOrgType()))
				&& (this.getDescription() == null ? other.getDescription() == null
						: this.getDescription().equals(other.getDescription()))
				&& (this.getIsAvailable() == null ? other.getIsAvailable() == null
						: this.getIsAvailable().equals(other.getIsAvailable()))
				&& (this.getPriority() == null ? other.getPriority() == null
						: this.getPriority().equals(other.getPriority()))
				&& (this.getCreateBy() == null ? other.getCreateBy() == null
						: this.getCreateBy().equals(other.getCreateBy()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateBy() == null ? other.getUpdateBy() == null
						: this.getUpdateBy().equals(other.getUpdateBy()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getIsDeleted() == null ? other.getIsDeleted() == null
						: this.getIsDeleted().equals(other.getIsDeleted()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_organization
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSoId() == null) ? 0 : getSoId().hashCode());
		result = prime * result + ((getParentSoId() == null) ? 0 : getParentSoId().hashCode());
		result = prime * result + ((getOrgCode() == null) ? 0 : getOrgCode().hashCode());
		result = prime * result + ((getOrgName() == null) ? 0 : getOrgName().hashCode());
		result = prime * result + ((getOrgType() == null) ? 0 : getOrgType().hashCode());
		result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
		result = prime * result + ((getIsAvailable() == null) ? 0 : getIsAvailable().hashCode());
		result = prime * result + ((getPriority() == null) ? 0 : getPriority().hashCode());
		result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_organization
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", soId=").append(soId);
		sb.append(", parentSoId=").append(parentSoId);
		sb.append(", orgCode=").append(orgCode);
		sb.append(", orgName=").append(orgName);
		sb.append(", orgType=").append(orgType);
		sb.append(", description=").append(description);
		sb.append(", isAvailable=").append(isAvailable);
		sb.append(", priority=").append(priority);
		sb.append(", createBy=").append(createBy);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateBy=").append(updateBy);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", isDeleted=").append(isDeleted);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}